name: First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create Deployment Folder
        run: mkdir deployment

      - name: Copy App to Deployment Folder
        run: cp app.txt deployment
      
      - name: Show Deployment Files 
        run: ls -la deployment
