name: Azure CI/CD Integration

on:
  push:
    branches:
      - main

jobs:
  azure-login-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure CLI Command
        run: az group list --output table
